CREATE TABLE "basketball_matches" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "basketball_matches_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"match_id" bigint,
	"league_gid" bigint,
	"league_id" bigint,
	"league_name" varchar(255),
	"file_group" varchar(100),
	"match_status" varchar(50),
	"match_date" date,
	"match_time" time,
	"timer" varchar(20),
	"h_team_id" bigint,
	"h_team_name" varchar(255),
	"h_team_score" integer,
	"h_team_q1" integer,
	"h_team_q2" integer,
	"h_team_q3" integer,
	"h_team_q4" integer,
	"h_team_ot" integer,
	"a_team_id" bigint,
	"a_team_name" varchar(255),
	"a_team_score" integer,
	"a_team_q1" integer,
	"a_team_q2" integer,
	"a_team_q3" integer,
	"a_team_q4" integer,
	"a_team_ot" integer,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "basketball_matches_match_id_unique" UNIQUE("match_id")
);
